name: MyEssentials
main: chuckl0r.MyEssentials
version: 1.1.5-Beta
author: Chuckl0r

commands:
    wispi:
        description: Der Whisper Befehl.
        usage: /<command> [Player] [Nachricht]
        permission: chuckl0r.MyEssentials.wispi
        permission-message: Du hast das Recht <permission> nicht!
    gmode:
        description: Der GameMode Changer.
        usage: /<command> ([GameMode / Spieler]) ([GameMode])
        permission: chuckl0r.MyEssentials.gamemode
        permission-message: Du hast das Recht <permission> nicht!
    tm:
        description: Zeit Manager.
        usage: /<command> [Zeit]
        permission: chuckl0r.MyEssentials.time
        permission-message: Du hast das Recht <permission> nicht!
    MyEssentials:
        description: Plugin Info.
        usage: /<command> [info]
    g:
        description: Item adder.
        usage: /<command> [itemId] [Menge]
        permission: chuckl0r.MyEssentials.give
        permission-message: Du hast das Recht <permission> nicht!
    w:
        description: Wetter Manager.
        usage: /<command> [Wetter]
        permission: chuckl0r.MyEssentials.wetter
        permission-message: Du hast das Recht <permission> nicht!
    ws:
        description: Wetter Manager.
        usage: /<command>
        permission: chuckl0r.MyEssentials.wetter.sonne
        permission-message: Du hast das Recht <permission> nicht!
    wr:
        description: Wetter Manager.
        usage: /<command>
        permission: chuckl0r.MyEssentials.wetter.regen
        permission-message: Du hast das Recht <permission> nicht!
    wst:
        description: Wetter Manager.
        usage: /<command>
        permission: chuckl0r.MyEssentials.wetter.sturm
        permission-message: Du hast das Recht <permission> nicht!
    tel:
        description: Wetter Manager.
        usage: /<command>
        permission: chuckl0r.MyEssentials.teleport
        permission-message: Du hast das Recht <permission> nicht!
    h:
        description: Der Heiler.
        usage: /<command> ([Spieler])
        permission: chuckl0r.MyEssentials.heal
        permission-message: Du hast das Recht <permission> nicht!
    crazy:
        description: Crazy Name.
        usage: /<command>
        permission: chuckl0r.MyEssentials.crazy
        permission-message: Du hast das Recht <permission> nicht!